version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: $Docker_login
          password: $Docker_password
    steps:
      - checkout
      - run: mvn clean install

  test:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: $Docker_login
          password: $Docker_password
    steps:
      - checkout
      - run: mvn test

  javadoc:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: $Docker_login
          password: $Docker_password
    steps:
      - checkout
      - run: javadoc:javadoc

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - javadoc:
          requires:
            - build
