version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
      - image: 'circleci/openjdk:11-jdk'
        auth:
          username: $Docker_login
          password: $Docker_password
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command:
            mvn verify sonar:sonar -Dsonar.projectKey=projekteszkozok5_intergalactic_fighters
            mvn clean install
      - persist_to_workspace:
         root: ./
         paths:
           - docs/

  test:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: $Docker_login
          password: $Docker_password
    steps:
      - checkout
      - run: mvn test

  javadoc:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: $Docker_login
          password: $Docker_password
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "13:97:c7:db:18:e5:bf:7c:a2:06:1a:d5:5f:d7:11:bd"
      - run: mvn javadoc:javadoc
      - store_artifacts:
          path: docs/
workflows:
  version: 2

  build-then-test:
    jobs:
      - build:
          context: SonarCloud
      - test:
          requires:
            - build
      - javadoc:
          requires:
            - build
