version: 2.1

jobs:
  build:
    steps:
      - checkout
      - run: mvn clean install

  test:
    steps:
      - checkout
      - run: mvn test

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build